site_name: TV06 CoreXY

nav:
  - Home: index.md
  - First Steps: about.md
  - Build Guide:
    - Toolhead: buildguide/toolhead.md
    - Frame: buildguide/frame.md
    - Gantry Mounting: buildguide/gantry.md
    - Electronics: buildguide/electronics.md
    - Enclosure: buildguide/enclosure.md
    - Finishing Touches: buildguide/finish.md
  - Sourcing Guide: sourcing.md

theme:
  language: en
  name: material
  features: 
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.expand
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xVtU45zTrk

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables

repo_url: https://github.com/VectorForce3D/TV06_XY
